"""create highlights table

Revision ID: 259056b7274b
Revises: a51fbc525365
Create Date: 2026-08-29 17:22:11.043352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '259056b7274b'
down_revision: Union[str, Sequence[str], None] = 'a51fbc525365'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('highlights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('youtube_url', sa.String(length=2048), nullable=False),
    sa.Column('youtube_video_id', sa.String(length=20), nullable=False),
    sa.Column('source_title', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('pending', 'downloading', 'analyzing', 'rendering', 'completed', 'failed', name='highlight_status'), nullable=False),
    sa.Column('source_duration_seconds', sa.Float(), nullable=True),
    sa.Column('highlight_duration_seconds', sa.Float(), nullable=True),
    sa.Column('output_url', sa.String(length=2048), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_highlights_id'), 'highlights', ['id'], unique=False)
    op.create_index(op.f('ix_highlights_user_id'), 'highlights', ['user_id'], unique=False)
    op.create_index(op.f('ix_highlights_youtube_video_id'), 'highlights', ['youtube_video_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_highlights_youtube_video_id'), table_name='highlights')
    op.drop_index(op.f('ix_highlights_user_id'), table_name='highlights')
    op.drop_index(op.f('ix_highlights_id'), table_name='highlights')
    op.drop_table('highlights')
    # ### end Alembic commands ###
    # Postgres doesn't auto-drop an ENUM type when the table using it is
    # dropped; drop it explicitly (harmless no-op on SQLite).
    sa.Enum(name='highlight_status').drop(op.get_bind(), checkfirst=True)
